import pandas as pd
import numpy as np
import plotly.graph_objects as go

''' 
    Generates a 3D visualization of the track using the CSV file generated by generate_track_csv.py.
    
    Go check the self.obs keys in StayInMiddleAgent.py to understand the data structure. 
    It contains some hidden gems data the tracks ;)'''

# Function to plot the track from CSV interactively
def plot_track_3d(csv_file):
    df = pd.read_csv(csv_file)
    
    # Extract coordinates
    center_x, center_y, center_z = df['Center_X'], df['Center_Y'], df['Center_Z']
    left_x, left_y, left_z = df['Left_X'], df['Left_Y'], df['Left_Z']
    right_x, right_y, right_z = df['Right_X'], df['Right_Y'], df['Right_Z']
    
    # Create traces for center, left, and right boundaries
    fig = go.Figure()
    
    fig.add_trace(go.Scatter3d(x=center_x, y=center_y, z=center_z, mode='lines', name='Center Line', line=dict(color='blue')))
    fig.add_trace(go.Scatter3d(x=left_x, y=left_y, z=left_z, mode='lines', name='Left Boundary', line=dict(color='red')))
    fig.add_trace(go.Scatter3d(x=right_x, y=right_y, z=right_z, mode='lines', name='Right Boundary', line=dict(color='green')))
    
    # Create surface for track
    for i in range(len(left_x) - 1):
        fig.add_trace(go.Mesh3d(
            x=[left_x[i], left_x[i+1], right_x[i+1], right_x[i]],
            y=[left_y[i], left_y[i+1], right_y[i+1], right_y[i]],
            z=[left_z[i], left_z[i+1], right_z[i+1], right_z[i]],
            color='gray', opacity=0.5, showscale=False
        ))
    
    fig.update_layout(
        title='3D Track Visualization',
        scene=dict(xaxis_title='X', yaxis_title='Y', zaxis_title='Z'),
        margin=dict(l=0, r=0, b=0, t=40)
    )
    
    fig.show()


import os
current_dir = os.path.dirname(os.path.abspath(__file__))  # I'm generating the graph in the script's directory, but that can be changed later ofc
csv_path = os.path.join(current_dir, "track_data.csv")
plot_track_3d(csv_path)
