import pandas as pd
import numpy as np
import plotly.graph_objects as go
import os

# pip install plotly
# pip install -U kaleido

''' 
    Generates a 3D visualization as well as a png image of the track using the CSV file generated by generate_track_csv.py.
    
    Go check the self.obs keys in StayInMiddleAgent.py to understand the data structure. 
    It contains some hidden gems data the tracks ;)'''

# Set up directories
csv_base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "ZZ_csv_base"))
graph_base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "ZZ_graph_base"))
os.makedirs(graph_base_dir, exist_ok=True)

def plot_track_3d(track_name):
    """Generates a 3D visualization of a track from its CSV data."""
    csv_file = os.path.join(csv_base_dir, f"{track_name}_track_data.csv")
    df = pd.read_csv(csv_file)

    fig = go.Figure()
    fig.add_trace(go.Scatter3d(x=df['Center_X'], y=df['Center_Y'], z=df['Center_Z'], mode='lines', name='Center Line', line=dict(color='blue')))
    fig.add_trace(go.Scatter3d(x=df['Left_X'], y=df['Left_Y'], z=df['Left_Z'], mode='lines', name='Left Boundary', line=dict(color='red')))
    fig.add_trace(go.Scatter3d(x=df['Right_X'], y=df['Right_Y'], z=df['Right_Z'], mode='lines', name='Right Boundary', line=dict(color='green')))

    for i in range(len(df) - 1):
        fig.add_trace(go.Mesh3d(
            x=[df['Left_X'][i], df['Left_X'][i+1], df['Right_X'][i+1], df['Right_X'][i]],
            y=[df['Left_Y'][i], df['Left_Y'][i+1], df['Right_Y'][i+1], df['Right_Y'][i]],
            z=[df['Left_Z'][i], df['Left_Z'][i+1], df['Right_Z'][i+1], df['Right_Z'][i]],
            color='gray', opacity=0.5, showscale=False
        ))

    output_image = os.path.join(graph_base_dir, f"{track_name}_track_visualization.png")
    fig.write_image(output_image)
    print(f"Graph saved as {output_image}")
    fig.show()

# Plot track
plot_track_3d("xr591") # change the track name to visualize a different track!!


