name: Run Track Tests and Generate 3D Graphs

on:
  push:
  pull_request:
  workflow_dispatch:  # Allows manual execution

jobs:
  run-track-tests:
    runs-on: ubuntu-latest  # You can change to macOS or Windows if needed

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3  # Fetches your repo

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Adjust if needed

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure this file exists and lists dependencies
        pip install plotly matplotlib pandas pytest

    - name: Run Track Tests
      run: |
        pytest tests/tests_track/ --disable-warnings

    - name: Run Graph Generation Scripts
      run: |
        python tests/tests_track/simple_track_map/generate_track_map.py
        python tests/tests_track/simple_track_map/generate_track_csv.py
        python tests/tests_track/with_nodes/generate_track_with_nodes.py
        python tests/tests_track/agent_path/generate_agent_path_plot.py

    - name: Upload Graphs as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: track-graphs
        path: |
          tests/tests_track/**/*.png
          tests/tests_track/**/*.csv
